modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Adventure%20Mode%20Tweaks"
logoFile="icon.png"

[[mods]]
modId="adventuremodetweaks"
version="1.1"
displayName="Adventure Mode Tweaks"
displayURL="https://serilum.com/mod/adventure-mode-tweaks"
authors="Rick South"
description='''Various Adventure Mode mechanic improvements! Paintings, Item Frames, Minecarts, Boats and more.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., t128, Tyler Behl, William Innes, XAgent, ตัวตรึง พระนคร   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.adventuremodetweaks]]
    modId="collective"
    mandatory=true
    versionRange="[8.13,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.adventuremodetweaks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11]"
    ordering="NONE"
    side="BOTH"
